# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-33968bc4-9882-43bf-9667-080e3ed5b6db";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-33968bc4-9882-43bf-9667-080e3ed5b6db".device = "/dev/disk/by-uuid/33968bc4-9882-43bf-9667-080e3ed5b6db";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A6D9-317B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
    {
      device = "/dev/mapper/swap";
      encrypted = {
        enable = true;
        label = "swap";
        blkDev = "/dev/disk/by-partuuid/60557343-5de0-4f5d-a8ed-646056099c52";
      };
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
