{
  imports = [
    ./command-palette
    ./reload-theme
    ./rofi-nix-helper
    ./sounds
    ./brightness
    ./suspend-and-screen-lock
    ./hyprpanel
    ./zen-mode
    ./blue-light-filter
    ./theme-switch
    ./screenshot
    ./system
    ./openvpn
    ./lazycommit
    ./fileinfo
    ./package-audit
    ./reh
  ];
}
